#pragma once
#include <cmath>
#include <algorithm>

/**
 * VintageProcessor — Post-chorus "vintage mastering" chain
 * Inspired by the Lemuria/Legowelt audio processing chain:
 *   1. Drive / Saturation (warm analog coloring, like Auto Filter drive)
 *   2. Vintage EQ (low warmth, mid scoop, presence boost, high rolloff)
 *   3. Bass Mono (M/S processing — mono below ~120Hz for tight low end)
 *   4. Soft-knee compressor (glue / sustain — tames peaks, adds body)
 *
 * Single "Amount" control (0-1) scales the intensity of all stages.
 * At 0 the signal passes through clean; at 1 you get the full vintage chain.
 */
class VintageProcessor
{
public:
    void setSampleRate(double sr)
    {
        sampleRate = std::max(sr, 1.0);
        // Precompute filter coefficients for the fixed EQ bands + saturator pre/de-emphasis
        computeEQCoeffs();
        computeBassMonoCoeffs();
        computeSatEmphasisCoeffs();
    }

    void setEnabled(bool on) { enabled = on; }
    bool isEnabled() const { return enabled; }

    void setAmount(float a) { amount = std::clamp(a, 0.0f, 1.0f); }
    float getAmount() const { return amount; }

    void reset()
    {
        // EQ filter states
        for (int ch = 0; ch < 2; ++ch)
        {
            for (int band = 0; band < 4; ++band)
            {
                eqState[ch][band].z1 = 0.0f;
                eqState[ch][band].z2 = 0.0f;
            }
        }
        // Bass mono crossover state
        bassLPStateL.z1 = bassLPStateL.z2 = 0.0f;
        bassLPStateR.z1 = bassLPStateR.z2 = 0.0f;
        bassHPStateL.z1 = bassHPStateL.z2 = 0.0f;
        bassHPStateR.z1 = bassHPStateR.z2 = 0.0f;
        // Compressor state
        compEnvelope = 0.0f;
        // P38: saturator pre/de-emphasis + DC blocker state
        preEmphStateL.z1 = preEmphStateL.z2 = 0.0f;
        preEmphStateR.z1 = preEmphStateR.z2 = 0.0f;
        deEmphStateL.z1 = deEmphStateL.z2 = 0.0f;
        deEmphStateR.z1 = deEmphStateR.z2 = 0.0f;
        dcBlockerXL = dcBlockerYL = 0.0f;
        dcBlockerXR = dcBlockerYR = 0.0f;
    }

    /**
     * Process a stereo pair in-place.
     */
    void process(float& left, float& right)
    {
        if (!enabled || amount < 0.001f)
            return;

        // === Stage 1: Tube-style multi-band saturation (P38 rewrite) ===
        // Pipeline: pre-emphasis → waveshaper (cubic+tanh blend with asymmetric
        // bias) → DC blocker → de-emphasis. Pre-emphasis pushes highs INTO
        // the non-linear stage so the saturator generates richer harmonics
        // there; de-emphasis restores the spectral balance afterwards but
        // keeps the harmonics — the classic dolby / tape / tube trick for
        // saturation that sounds open instead of dull and fuzzy.
        // The L/R channels use slightly asymmetric bias for a natural sense
        // of analog M/S width.
        {
            const float driveGain = 1.0f + amount * 3.5f;   // 1..4.5

            // Pre-emphasis: high-shelf boost (+6 dB above ~3 kHz) BEFORE drive.
            float preL = processBiquad(left,  preEmphCoeffs, preEmphStateL);
            float preR = processBiquad(right, preEmphCoeffs, preEmphStateR);

            // Multi-stage waveshaper. The cubic term is responsible for warm
            // 3rd-order harmonics (tube triode signature), the tanh limits
            // the overall excursion, and the asymmetric bias adds 2nd-order
            // harmonics (sweet / euphonic — the bit that makes saturation
            // feel "musical" rather than "distorted").
            const float biasL =  0.04f * amount;     // tiny positive DC offset L
            const float biasR = -0.04f * amount;     // tiny negative DC offset R (M/S asymmetry)
            float satL = tubeShaper(preL * driveGain + biasL) / driveGain;
            float satR = tubeShaper(preR * driveGain + biasR) / driveGain;

            // DC blocker — strips the bias offsets we injected (the harmonic
            // imprint stays, but no inaudible DC build-up reaches MASTER).
            satL = dcBlock(satL, dcBlockerXL, dcBlockerYL);
            satR = dcBlock(satR, dcBlockerXR, dcBlockerYR);

            // De-emphasis: high-shelf cut to invert the pre-emphasis. The
            // harmonics that were generated by the shaper stay above the cut
            // (they're broadband), while the original signal recovers its
            // pre-saturation balance. Net result: rich harmonics, no fizz.
            float deL = processBiquad(satL, deEmphCoeffs, deEmphStateL);
            float deR = processBiquad(satR, deEmphCoeffs, deEmphStateR);

            // Wet/dry blend — matches the EQ / bass-mono / compressor stages
            // below, so the SAT AMOUNT knob has a single coherent meaning:
            // 0 = fully dry, 1 = fully wet. Combined with the early-exit
            // guard at amount<0.001, the knob fade-in is click-free.
            const float wet = amount;
            const float dry = 1.0f - wet;
            left  = left  * dry + deL * wet;
            right = right * dry + deR * wet;
        }

        // === Stage 2: Vintage EQ ===
        // 4-band parametric EQ with fixed frequencies, scaled by amount:
        //   Band 0: Low shelf +2dB at 80Hz (warmth)
        //   Band 1: Bell -2.5dB at 400Hz Q=0.8 (mid scoop — clarity)
        //   Band 2: Bell +3dB at 5kHz Q=1.2 (presence boost)
        //   Band 3: High shelf -4dB at 10kHz (vintage rolloff)
        {
            // Scale EQ intensity by amount
            float eqMix = amount;
            float dryL = left, dryR = right;

            float wetL = left, wetR = right;
            for (int band = 0; band < 4; ++band)
            {
                wetL = processBiquad(wetL, eqCoeffs[band], eqState[0][band]);
                wetR = processBiquad(wetR, eqCoeffs[band], eqState[1][band]);
            }

            left  = dryL + (wetL - dryL) * eqMix;
            right = dryR + (wetR - dryR) * eqMix;
        }

        // === Stage 3: Bass Mono (M/S below 120Hz) ===
        // Split into low (<120Hz) and high (>120Hz)
        // Mono the low band, keep high band stereo
        {
            float bassMix = amount;  // scale effect with amount

            // Low-pass left/right
            float lowL = processBiquad(left,  bassLPCoeffs, bassLPStateL);
            float lowR = processBiquad(right, bassLPCoeffs, bassLPStateR);

            // High-pass left/right (original minus low = high)
            float highL = left - lowL;
            float highR = right - lowR;

            // Mono the bass
            float bassMono = (lowL + lowR) * 0.5f;

            // Recombine: mono bass + stereo highs
            float monoL = bassMono + highL;
            float monoR = bassMono + highR;

            // Blend based on amount
            left  = left  + (monoL - left)  * bassMix;
            right = right + (monoR - right) * bassMix;
        }

        // === Stage 4: Soft-knee compressor / sustain ===
        // Simple envelope-following compressor for glue and sustain
        {
            float compMix = amount;
            float threshold = 0.3f;          // ~-10dB threshold
            float ratio = 2.0f + amount * 2.0f;  // 2:1 to 4:1
            float attack  = 0.005f;          // 5ms attack
            float release = 0.080f;          // 80ms release
            float makeupGain = 1.0f + amount * 0.5f;  // compensate gain reduction

            // Envelope follower (peak detection)
            float peak = std::max(std::abs(left), std::abs(right));
            float attackCoeff  = std::exp(-1.0f / (float)(sampleRate * attack));
            float releaseCoeff = std::exp(-1.0f / (float)(sampleRate * release));

            if (peak > compEnvelope)
                compEnvelope = attackCoeff * compEnvelope + (1.0f - attackCoeff) * peak;
            else
                compEnvelope = releaseCoeff * compEnvelope + (1.0f - releaseCoeff) * peak;

            // Flush denormal
            if (compEnvelope < 1.0e-15f) compEnvelope = 0.0f;

            // Compute gain reduction
            float gainReduction = 1.0f;
            if (compEnvelope > threshold)
            {
                // Soft-knee: smooth transition around threshold
                float overDb = 20.0f * std::log10(compEnvelope / threshold);
                float compressedDb = overDb / ratio;
                float reductionDb = overDb - compressedDb;
                gainReduction = std::pow(10.0f, -reductionDb / 20.0f);
            }

            // Apply compression with mix control
            float compGain = 1.0f + (gainReduction * makeupGain - 1.0f) * compMix;
            left  *= compGain;
            right *= compGain;
        }

        // P1-7: no final tanh here — the master path applies tanh AFTER master gain
        // (processBlock final stage), so this used to double-saturate. We rely on
        // the master soft-clip instead. If you ever want vintage-only saturation
        // re-enable here and remove the master tanh.
    }

private:
    double sampleRate = 44100.0;
    bool enabled = false;
    float amount = 0.5f;

    // === Asymmetric soft clipping (legacy — kept for reference) ===
    static float softClipAsym(float x)
    {
        if (x >= 0.0f)
            return std::tanh(x);
        else
            return std::tanh(x * 1.2f) / 1.2f;
    }

    // P38: musical tube-style waveshaper. Blends cubic non-linearity (rich
    // 3rd-order content) with tanh limiting (soft top-end clip). The blend
    // weight depends on the input magnitude so quiet signals stay close to
    // pure cubic (warm, low THD) and loud signals approach tanh (clean limit
    // without fold-over).
    static float tubeShaper(float x)
    {
        // Clamp extreme inputs so the cubic doesn't explode if the caller
        // forgets to gain-stage.
        if (x >  3.0f) x =  3.0f;
        if (x < -3.0f) x = -3.0f;
        const float ax = std::abs(x);
        // Cubic term: x - x^3/3 (a normalised triode-style soft saturator).
        // Capped so that |cubic(x)| ≤ 2/3 inside |x| ≤ 1 — then we lean on
        // tanh for anything past unit gain.
        const float cubic = x - (x * x * x) / 3.0f;
        const float limited = std::tanh(x);
        // Blend: 0 at low levels → ~0.4 at full scale → ~1 in overload.
        const float t = std::min(1.0f, ax * 0.6f);
        return cubic * (1.0f - t) + limited * t;
    }

    // P38: one-pole DC blocker (high-pass at ~5 Hz). Used to scrub the
    // intentional DC bias the saturator added for asymmetric harmonics.
    static float dcBlock(float in, float& xPrev, float& yPrev)
    {
        // y[n] = x[n] - x[n-1] + R * y[n-1], R≈0.9995 ⇒ corner ≈ 5 Hz @ 44.1kHz
        constexpr float R = 0.9995f;
        const float y = in - xPrev + R * yPrev;
        xPrev = in;
        yPrev = y;
        // Denormal flush
        return std::abs(y) < 1.0e-15f ? 0.0f : y;
    }

    // === Biquad filter infrastructure ===
    struct BiquadCoeffs
    {
        float b0 = 1.0f, b1 = 0.0f, b2 = 0.0f;
        float a1 = 0.0f, a2 = 0.0f;
    };

    struct BiquadState
    {
        float z1 = 0.0f, z2 = 0.0f;
    };

    static float processBiquad(float input, const BiquadCoeffs& c, BiquadState& s)
    {
        float output = c.b0 * input + s.z1;
        s.z1 = c.b1 * input - c.a1 * output + s.z2;
        s.z2 = c.b2 * input - c.a2 * output;

        // Flush denormals
        if (std::abs(s.z1) < 1.0e-15f) s.z1 = 0.0f;
        if (std::abs(s.z2) < 1.0e-15f) s.z2 = 0.0f;

        return output;
    }

    // === EQ: 4 bands ===
    BiquadCoeffs eqCoeffs[4];
    BiquadState  eqState[2][4];  // [channel][band]

    void computeEQCoeffs()
    {
        float sr = (float)sampleRate;
        // Band 0: Low shelf +2dB at 80Hz
        eqCoeffs[0] = makeLowShelf(80.0f, 2.0f, 0.7f, sr);
        // Band 1: Bell -2.5dB at 400Hz, Q=0.8
        eqCoeffs[1] = makePeakEQ(400.0f, -2.5f, 0.8f, sr);
        // Band 2: Bell +3dB at 5000Hz, Q=1.2
        eqCoeffs[2] = makePeakEQ(5000.0f, 3.0f, 1.2f, sr);
        // Band 3: High shelf -4dB at 10000Hz
        eqCoeffs[3] = makeHighShelf(10000.0f, -4.0f, 0.7f, sr);
    }

    // === Bass mono crossover at 120Hz ===
    BiquadCoeffs bassLPCoeffs;
    BiquadState  bassLPStateL, bassLPStateR;
    BiquadState  bassHPStateL, bassHPStateR;

    void computeBassMonoCoeffs()
    {
        float sr = (float)sampleRate;
        bassLPCoeffs = makeLowPass(120.0f, 0.707f, sr);
    }

    // === Compressor state ===
    float compEnvelope = 0.0f;

    // === P38: Saturator pre/de-emphasis + DC blocker state ===
    BiquadCoeffs preEmphCoeffs;   // +6 dB high-shelf @ ~3 kHz (into saturator)
    BiquadCoeffs deEmphCoeffs;    // -6 dB high-shelf @ ~3 kHz (after saturator)
    BiquadState  preEmphStateL, preEmphStateR;
    BiquadState  deEmphStateL,  deEmphStateR;
    // One-pole DC blocker memories (per channel)
    float dcBlockerXL = 0.0f, dcBlockerYL = 0.0f;
    float dcBlockerXR = 0.0f, dcBlockerYR = 0.0f;

    void computeSatEmphasisCoeffs()
    {
        float sr = (float)sampleRate;
        // Pre-emphasis: high-shelf BOOST +6 dB at 3 kHz, gentle Q so the
        // transition feels smooth.
        preEmphCoeffs = makeHighShelf(3000.0f,  6.0f, 0.65f, sr);
        // De-emphasis: matching CUT to invert the pre-emphasis on the dry
        // signal. The non-linearly generated harmonics survive this cut
        // because they're broadband above and below the shelf corner.
        deEmphCoeffs  = makeHighShelf(3000.0f, -6.0f, 0.65f, sr);
    }

    // === Biquad coefficient calculators (Audio EQ Cookbook formulas) ===

    static BiquadCoeffs makePeakEQ(float freq, float gainDb, float Q, float sr)
    {
        BiquadCoeffs c;
        float A = std::pow(10.0f, gainDb / 40.0f);
        float w0 = 2.0f * 3.14159265f * freq / sr;
        float sinW0 = std::sin(w0);
        float cosW0 = std::cos(w0);
        float alpha = sinW0 / (2.0f * Q);

        float a0 = 1.0f + alpha / A;
        c.b0 = (1.0f + alpha * A) / a0;
        c.b1 = (-2.0f * cosW0) / a0;
        c.b2 = (1.0f - alpha * A) / a0;
        c.a1 = (-2.0f * cosW0) / a0;
        c.a2 = (1.0f - alpha / A) / a0;
        return c;
    }

    static BiquadCoeffs makeLowShelf(float freq, float gainDb, float Q, float sr)
    {
        BiquadCoeffs c;
        float A = std::pow(10.0f, gainDb / 40.0f);
        float w0 = 2.0f * 3.14159265f * freq / sr;
        float sinW0 = std::sin(w0);
        float cosW0 = std::cos(w0);
        float alpha = sinW0 / (2.0f * Q);
        float sqrtA2alpha = 2.0f * std::sqrt(A) * alpha;

        float a0 = (A + 1.0f) + (A - 1.0f) * cosW0 + sqrtA2alpha;
        c.b0 = (A * ((A + 1.0f) - (A - 1.0f) * cosW0 + sqrtA2alpha)) / a0;
        c.b1 = (2.0f * A * ((A - 1.0f) - (A + 1.0f) * cosW0)) / a0;
        c.b2 = (A * ((A + 1.0f) - (A - 1.0f) * cosW0 - sqrtA2alpha)) / a0;
        c.a1 = (-2.0f * ((A - 1.0f) + (A + 1.0f) * cosW0)) / a0;
        c.a2 = ((A + 1.0f) + (A - 1.0f) * cosW0 - sqrtA2alpha) / a0;
        return c;
    }

    static BiquadCoeffs makeHighShelf(float freq, float gainDb, float Q, float sr)
    {
        BiquadCoeffs c;
        float A = std::pow(10.0f, gainDb / 40.0f);
        float w0 = 2.0f * 3.14159265f * freq / sr;
        float sinW0 = std::sin(w0);
        float cosW0 = std::cos(w0);
        float alpha = sinW0 / (2.0f * Q);
        float sqrtA2alpha = 2.0f * std::sqrt(A) * alpha;

        float a0 = (A + 1.0f) - (A - 1.0f) * cosW0 + sqrtA2alpha;
        c.b0 = (A * ((A + 1.0f) + (A - 1.0f) * cosW0 + sqrtA2alpha)) / a0;
        c.b1 = (-2.0f * A * ((A - 1.0f) + (A + 1.0f) * cosW0)) / a0;
        c.b2 = (A * ((A + 1.0f) + (A - 1.0f) * cosW0 - sqrtA2alpha)) / a0;
        c.a1 = (2.0f * ((A - 1.0f) - (A + 1.0f) * cosW0)) / a0;
        c.a2 = ((A + 1.0f) - (A - 1.0f) * cosW0 - sqrtA2alpha) / a0;
        return c;
    }

    static BiquadCoeffs makeLowPass(float freq, float Q, float sr)
    {
        BiquadCoeffs c;
        float w0 = 2.0f * 3.14159265f * freq / sr;
        float sinW0 = std::sin(w0);
        float cosW0 = std::cos(w0);
        float alpha = sinW0 / (2.0f * Q);

        float a0 = 1.0f + alpha;
        c.b0 = ((1.0f - cosW0) / 2.0f) / a0;
        c.b1 = (1.0f - cosW0) / a0;
        c.b2 = ((1.0f - cosW0) / 2.0f) / a0;
        c.a1 = (-2.0f * cosW0) / a0;
        c.a2 = (1.0f - alpha) / a0;
        return c;
    }
};
